project:
  type: website

format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: false
    sidebar: false
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    title: "Index"
    background: black
    foreground: white
    search: false
  page-footer:
    center: "© 2025 Yichen Zhou · [Contact](mailto:ethanzhou616@gmail.com)"